# Generated by Django 5.1.6 on 2025-02-12 20:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero', models.FloatField()),
                ('texto', models.CharField(max_length=100)),
                ('texto_grande', models.TextField()),
                ('json', models.JSONField()),
                ('boolean', models.BooleanField()),
                ('fecha_hoy', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
            },
        ),
        migrations.CreateModel(
            name='RelacionArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nombre_app.archivos')),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nombre_app.prueba')),
            ],
            options={
                'verbose_name': 'Relacion Archivos',
                'verbose_name_plural': 'Relaciones Archivos',
                'unique_together': {('id_archivo', 'id_prueba')},
            },
        ),
        migrations.AddField(
            model_name='prueba',
            name='archivo',
            field=models.ManyToManyField(related_name='pruebas', through='nombre_app.RelacionArchivos', to='nombre_app.archivos'),
        ),
    ]
